
#	$NetBSD: Makefile,v 1.5 2008/01/28 07:03:59 dholland Exp $
#	@(#)Makefile	8.1 (Berkeley) 3/31/94

PROG=	cfm_test		# Name of the program
MAN=					# No man page

LDADD+=	-lsys
DPADD+=	${LIBSYS}

.include <bsd.prog.mk>		# This is a program, not a library
